[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Layover Connections"
authors = [{name = "Alejandro", "Danish", email = "Insert Email here"}]
dynamic = ["version", "description"]
