# Generated by Django 4.1.5 on 2023-02-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layoverconnections', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
