# Generated by Django 4.1.5 on 2023-02-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layoverconnections', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userimage_1',
            field=models.ImageField(default='placeholder.jpg', upload_to='profile_pics'),
        ),
    ]
