# Generated by Django 4.1.5 on 2023-02-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layoverconnections', '0007_profile_userimage_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userimage_2',
            field=models.ImageField(default='placeholer.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userimage_3',
            field=models.ImageField(default='placeholer.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userimage_4',
            field=models.ImageField(default='placeholer.jpg', upload_to='profile_pics'),
        ),
    ]
