# Generated by Django 4.1.5 on 2023-03-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layoverconnections', '0008_profile_userimage_2_profile_userimage_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage_1',
            field=models.ImageField(default='placeholer.jpg', upload_to='profile_pics'),
        ),
    ]
